library(jsonlite)
library(httr2)
library(stringr)

# Save your API key in the file PaLM_AI_key.txt
MY_OPENAI_API_KEY <- NULL
  # readLines("C:/Users/dinov/Desktop/Ivo.dir/Research/Proposals/SOCR/2020/RShiny_Apps_2020/SOCR_AI_Bot/SOCR_AI_Bot_V1.5/api_key.txt")
# Sys.setenv(OPENAI_API_KEY = MY_OPENAI_API_KEY)

# Edit the following line with the endpoint of the API.
# You can find this in the Azure portal under "Keys and Endpoint".
# MY_ENDPOINT <- "https://openai-test-20230120.openai.azure.com/"
MY_ENDPOINT <- "https://api.openai.com/v1"

# Edit the following line with the model you want to use.
# You can find options in the Azure portal under "Model Deployments"
MY_DEPLOYMENT <- language_model  # "text-davinci-003"

# https://api.openai.com/v1/chat/completions 

openai <- function(prompt, temperature=1,top_p=0.5,max_tokens=100,stop="null",
    OPENAI_API_KEY=MY_OPENAI_API_KEY,
    ENDPOINT=MY_ENDPOINT,
    model=MY_DEPLOYMENT, print.it=TRUE) {
    # openai(prompt) returns a string of text generated by the OpenAI API
    # ARGUMENTS:
    # prompt: a string of text to prompt the API with (Do not include single quotes)

    # VALUE:
    # the completion generated by the OpenAI API 
    # in addition, if print.it=TRUE (the defualt), the completion is printed
    # to the console minus any leading whitespace

    # Example:
    # openai("The quick brown fox jumps over the lazy dog. Translate into French:")
     

    req <- request(ENDPOINT) %>%
        # req_url_path_append("openai/deployments") %>% 
      req_url_path_append("/chat/completions/") %>%
        req_url_path_append(model) %>%
        req_url_path_append("completions") # %>%
        # req_url_query("api-version"="2022-12-01")

    # newlines in the prompt confuse the API, so use toJSON to encode as \n        
    payload <- paste0('{
    "prompt": ', toJSON(prompt, auto_unbox=TRUE), ', 
    "max_tokens": ',max_tokens,',
    "temperature": ', temperature, ',
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "top_p": ', top_p, ',
    "best_of": 1,
    "stop": ',stop,' 
    }')

    req <- req %>% req_headers(
            `api-key` = OPENAI_API_KEY,
        ) %>% 
        req_body_raw(payload, "application/json") 
    
    #print(req_dry_run(req)) 
    result <- req %>% req_perform() %>% resp_body_json() 
    completion <- result$choices[[1]]$text
    output <- str_trim(completion) # remove leading and trailing whitespace
    if (print.it) cat(output,"\n")
    return(invisible(completion))
}

#Examples:
#openai("tell me a joke")
#openai("Your favorite number is 5. Pick a number between 1 and 10. Go:", top_p=1)
#openai("Complete this sentence: The best flavor of ice cream is ", top_p=0.9)
